### ISSUE TITLE
support pre-fetching of reads and variants for cluster computing use cases

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/utils-java#15]
. . . for Spark and Dataflow jobs operating over shards of reads or variants.

@kwestbrooks what would your specific recommendation be?

**Comment by kwestbrooks** [comment]
Whatever the solution is, it ought to be coded in a type-agnostic way, and have instances for each "search" method on the backend. Paginator is coded like this - all the magic happens in a generic method that only cares about the pageToken/nextPageToken protocol, and then there are paginator instances for each search method, parameterized with the appropriate types.

Just brainstorming here:
One way to do this is to shard each query into pieces. For example, if someone is requesting all the reads on chromosome 1 from position 0 to 100,000,000, you might imagine 100 simultaneous queries, each on fetching a disjoint set of results, say, the first one fetches the first million, the second one fetches the second million, as so on and so forth. Each query could spill its output to temp files, and you'd have a final fancy iterator that stitches all the results back together by doing a logical concat across the temp files and reading the data back from disk into memory. So, the performance for the first million positions is similar to the single threaded case, but then suddenly we speed up loading data from temp files instead of the API backend.

**Comment by deflaux** [comment]
This was implemented by @ssgross and @Careyjmac via the new support for GRPC.
